/* The cypress studio is still an experimental feature. We enable it in the cypress.config, and when we run a new test,
next to the name we used for the test there is a magic wand

That magic wand, will make whatever is defined in the test, such as visiting the page, and allow us to click on the elements
check if its visible, or if it has the expected test and so on. And by finishing our tests, we click on save and it will
reflect on the file we handled. */

describe("studio", () => {
  it("Exemplo do cypress studio", () => {
    cy.visit("https://example.cypress.io");
    /* ==== Generated with Cypress Studio ==== */
    cy.get("h1").click();
    cy.get("h1").should("be.visible");
    cy.get("h1").click();
    cy.get("h1").should("have.text", "Kitchen Sink");
    cy.get(".banner > .container").click();
    cy.get("h1").click();
    /* ==== End Cypress Studio ==== */
  });

  /* ==== Test Created with Cypress Studio ==== */
  it("Deve logar com sucesso", () => {
    /* ==== Generated with Cypress Studio ==== */
    cy.visit("http://localhost:3000");
    cy.get("#email").type("papito@webdojo.com");
    cy.get("#password").type("katana123");
    // cy.get(".bg-\\[\\#8257E5\\]").click(); // Bad practice generated by the studio
    cy.contains("button", "Entrar").click();
    cy.get('[data-cy="user-name"]').should("have.text", "Fernando Papito");
    /* ==== End Cypress Studio ==== */
  });
});
